version: "3.7"
services:
  db:
    image: database-image
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api_database
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    image: api-image
    volumes: 
      - ./api:/home/node/app
    depends_on:
      - db
    links: 
      - db
    ports:
      - "4000:4000"
  web:
    image: website-image
    volumes: 
      - ./website:/var/www/html
    depends_on: 
      - api
    links: 
      - api
    ports: 
      - "8888:80"